#!/usr/bin/env python3
"""Fail-closed, offline gate for the pinned rescue kernel's kmod-mtd-rw.

This reads artifacts only. It never invokes a package manager, module loader,
shell maintainer script, or router. The caller supplies a trusted reference .ko
extracted from the separately hash-verified original rescue image.
"""
import argparse
import gzip
import hashlib
import io
import json
from pathlib import Path
import re
import shutil
import struct
import tarfile
import tempfile

KERNEL_RELEASE = '6.6.133'
KERNEL_ABI = '030ad1570833e99b365a217a0ba91204'
KERNEL_DEPENDENCY = f'{KERNEL_RELEASE}~{KERNEL_ABI}-r1'
ARCHITECTURE = 'aarch64_cortex-a53'
MODULE_PATH = f'lib/modules/{KERNEL_RELEASE}/mtd-rw.ko'
MAX_BYTES = 32 * 1024 * 1024

# Exact wrappers generated by include/package-pack.mk at source-lock.json's
# ec9ef10efc65da1e6d1de4e2c043c0e13d08eed8. Its default_postinst calls
# kmodloader only for /etc/modules.d/ entries, which this gate disallows.
# Package-specific hooks (postinst-pkg, etc.) are never accepted.
STOCK_SCRIPTS = {
    'postinst': b'''#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
''',
    'prerm': b'''#!/bin/sh
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_prerm $0 $@
''',
}


def read_limited(path, limit=MAX_BYTES):
    with Path(path).open('rb') as stream:
        data = stream.read(limit + 1)
    if len(data) > limit:
        raise ValueError(f'Input exceeds {limit} bytes: {path}')
    return data


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def archive_path(name, directory):
    if not name or name.startswith('/') or '\\' in name or ':' in name:
        raise ValueError(f'Unsafe archive path: {name!r}')
    while name.startswith('./'):
        name = name[2:]
    if directory:
        name = name.rstrip('/')
        if name in ('', '.'):
            return ''
    parts = name.split('/')
    if any(part in ('', '.', '..') for part in parts):
        raise ValueError(f'Unsafe archive path: {name!r}')
    if not re.fullmatch(r'[A-Za-z0-9_+./-]+', name):
        raise ValueError(f'Unsupported archive path: {name!r}')
    return name


def read_tar_gz(data):
    """Return regular files and directory names, without extracting anything."""
    if not data.startswith(b'\x1f\x8b') or len(data) > MAX_BYTES:
        raise ValueError('Expected bounded gzip-compressed OpenWrt tar archive')
    try:
        with gzip.GzipFile(fileobj=io.BytesIO(data)) as stream:
            raw = stream.read(MAX_BYTES + 1)
        if len(raw) > MAX_BYTES:
            raise ValueError('Archive decompression limit exceeded')
        files, directories, seen = {}, set(), set()
        total = 0
        with tarfile.open(fileobj=io.BytesIO(raw), mode='r:') as archive:
            for item in archive:
                if len(seen) >= 64:
                    raise ValueError('Too many archive entries')
                name = archive_path(item.name, item.isdir())
                if name in seen:
                    raise ValueError(f'Duplicate archive path: {name!r}')
                seen.add(name)
                if item.pax_headers or item.mode & 0o7000:
                    raise ValueError(f'Unexpected archive metadata: {name!r}')
                if item.isdir():
                    if item.size != 0:
                        raise ValueError('Directory has a nonempty payload')
                    directories.add(name)
                elif item.isreg():
                    total += item.size
                    if item.size < 0 or total > MAX_BYTES:
                        raise ValueError('Archive payload limit exceeded')
                    stream = archive.extractfile(item)
                    if stream is None:
                        raise ValueError('Unreadable archive entry')
                    content = stream.read(item.size + 1)
                    if len(content) != item.size:
                        raise ValueError('Truncated archive entry')
                    files[name] = content
                else:
                    raise ValueError(f'Archive link or special file is forbidden: {name!r}')
        return files, directories
    except (EOFError, OSError, tarfile.TarError) as error:
        raise ValueError(f'Invalid gzip/tar archive: {error}') from error


def parse_control(data):
    try:
        text = data.decode('utf-8')
    except UnicodeError as error:
        raise ValueError('Package control is not UTF-8') from error
    if '\0' in text or '\r' in text:
        raise ValueError('Invalid package control characters')
    fields, last = {}, None
    for line in text.splitlines():
        if not line:
            continue
        if line[0].isspace():
            if last != 'Description':
                raise ValueError('Only the description may have continuation lines')
            fields[last] += '\n' + line
            continue
        key, separator, value = line.partition(':')
        if not separator or not re.fullmatch(r'[A-Za-z][A-Za-z0-9-]*', key) or key in fields:
            raise ValueError('Malformed or duplicate package control field')
        fields[key], last = value.strip(), key
    if fields.get('Package') != 'kmod-mtd-rw':
        raise ValueError('Package name must be kmod-mtd-rw')
    if fields.get('Architecture') != ARCHITECTURE:
        raise ValueError('Package architecture does not match rescue')
    if not fields.get('Version'):
        raise ValueError('Missing package version')
    dependencies = [part.strip() for part in fields.get('Depends', '').split(',')]
    # Only the locked kernel is needed by this package. Extra dependencies or
    # alternatives could cause a package manager to act outside this artifact.
    expected = rf'kernel\s*\(\s*=\s*{re.escape(KERNEL_DEPENDENCY)}\s*\)'
    if len(dependencies) != 1 or re.fullmatch(expected, dependencies[0]) is None:
        raise ValueError('Package must depend on the complete exact locked kernel version')
    return fields


def inspect_ipk(data):
    # The locked scripts/ipkg-build uses gzip(tar), not the ar container used by
    # Debian and some other ipk builders. Accept this source's format only.
    outer, directories = read_tar_gz(data)
    if set(outer) != {'debian-binary', 'control.tar.gz', 'data.tar.gz'} or directories - {''}:
        raise ValueError('Unexpected outer ipk contents')
    if outer['debian-binary'] != b'2.0\n':
        raise ValueError('Unsupported ipk format version')
    control, directories = read_tar_gz(outer['control.tar.gz'])
    if directories - {''} or 'control' not in control or set(control) - {'control', *STOCK_SCRIPTS}:
        raise ValueError('Unexpected control files or package maintainer hooks')
    for name, expected in STOCK_SCRIPTS.items():
        if name in control and control[name] != expected:
            raise ValueError(f'Unrecognized maintainer script: {name}')
    fields = parse_control(control['control'])
    payload, directories = read_tar_gz(outer['data.tar.gz'])
    allowed_dirs = {'', 'lib', 'lib/modules', f'lib/modules/{KERNEL_RELEASE}'}
    if set(payload) != {MODULE_PATH} or directories - allowed_dirs:
        raise ValueError('Payload must contain only mtd-rw.ko and its parent directories; no autoload')
    return fields, payload[MODULE_PATH], sorted(set(control) & set(STOCK_SCRIPTS))


def span(data, offset, size):
    if offset < 0 or size < 0 or offset + size > len(data):
        raise ValueError('ELF data extends outside the file')
    return data[offset:offset + size]


def cstring(data, offset):
    if offset < 0 or offset >= len(data):
        raise ValueError('ELF string offset outside its table')
    end = data.find(b'\0', offset)
    if end == -1:
        raise ValueError('Unterminated ELF string')
    try:
        return data[offset:end].decode('ascii')
    except UnicodeError as error:
        raise ValueError('Non-ASCII ELF metadata') from error


def inspect_elf(data):
    if len(data) < 64 or data[:7] != b'\x7fELF\x02\x01\x01':
        raise ValueError('Module must be a little-endian ELF64 file')
    header = struct.unpack('<16sHHIQQQIHHHHHH', data[:64])
    _, kind, machine, version, _, _, shoff, _, ehsize, _, _, shsize, shcount, shstrings = header
    if (kind, machine, version, ehsize, shsize) != (1, 183, 1, 64, 64):
        raise ValueError('Module must be ELF64 ET_REL for EM_AARCH64')
    if not 1 < shcount <= 4096 or not 0 < shstrings < shcount:
        raise ValueError('Unsupported or invalid ELF section table')
    table = span(data, shoff, shcount * shsize)
    sections = [struct.unpack('<IIQQQQIIQQ', table[i:i + 64]) for i in range(0, len(table), 64)]
    if sections[shstrings][1] != 3:
        raise ValueError('Invalid section name table')
    names = span(data, sections[shstrings][4], sections[shstrings][5])
    by_name = {}
    for section in sections:
        name = cstring(names, section[0])
        if name and name in by_name:
            raise ValueError(f'Duplicate ELF section: {name}')
        if section[1] != 8:  # SHT_NOBITS occupies memory, not file bytes.
            span(data, section[4], section[5])
        if name:
            by_name[name] = section
    if '.modinfo' not in by_name or by_name['.modinfo'][1] != 1:
        raise ValueError('Module lacks .modinfo')
    section = by_name['.modinfo']
    info = span(data, section[4], section[5])
    if not info.endswith(b'\0'):
        raise ValueError('Unterminated .modinfo')
    metadata = {}
    for item in info.split(b'\0'):
        if not item:
            continue
        try:
            key, value = item.decode('ascii').split('=', 1)
        except (UnicodeError, ValueError) as error:
            raise ValueError('Invalid .modinfo field') from error
        metadata.setdefault(key, []).append(value)
    if len(metadata.get('vermagic', [])) != 1:
        raise ValueError('Module must have exactly one vermagic')
    strong, weak = set(), set()
    symtabs = [section for section in sections if section[1] == 2]
    if len(symtabs) != 1:
        raise ValueError('Module must have exactly one ELF symbol table')
    for section in symtabs:
        size, link, entsize = section[5], section[6], section[9]
        if entsize != 24 or not size or size % entsize or not 0 < link < shcount or sections[link][1] != 3:
            raise ValueError('Invalid ELF symbol table')
        strings = span(data, sections[link][4], sections[link][5])
        symbols = span(data, section[4], size)
        for offset in range(0, len(symbols), 24):
            st_name, st_info, _, st_shndx, _, _ = struct.unpack('<IBBHQQ', symbols[offset:offset + 24])
            name = cstring(strings, st_name)
            if st_shndx == 0 and name:
                binding = st_info >> 4
                if binding == 1:
                    strong.add(name)
                elif binding == 2:
                    weak.add(name)
                else:
                    raise ValueError(f'Unsupported undefined symbol binding: {name}')
    return {'vermagic': metadata['vermagic'][0], 'modinfo': metadata,
            'undefined_symbols': sorted(strong), 'undefined_weak_symbols': sorted(weak),
            'elf_class': 'ELF64', 'elf_data': 'little-endian',
            'elf_machine': 'EM_AARCH64', 'elf_type': 'ET_REL'}


def read_exports(data):
    try:
        text = data.decode('ascii')
    except UnicodeError as error:
        raise ValueError('Module.symvers is not ASCII') from error
    exports = {}
    for line in text.splitlines():
        fields = line.split()
        if not fields:
            continue
        if len(fields) not in (4, 5) or not re.fullmatch(r'0x[0-9a-fA-F]{8}', fields[0]):
            raise ValueError('Malformed Module.symvers')
        crc, name, provider, export_type = fields[:4]
        if name in exports or not export_type.startswith('EXPORT_SYMBOL'):
            raise ValueError('Duplicate or malformed Module.symvers export')
        exports[name] = {'crc': crc, 'provider': provider, 'export_type': export_type,
                         'namespace': fields[4] if len(fields) == 5 else ''}
    if not exports:
        raise ValueError('Module.symvers is empty')
    return exports


def validate(ipk, reference_module, kernel_build, out):
    ipk, reference_module, kernel_build, out = map(Path, (ipk, reference_module, kernel_build, out))
    if out.exists() or out.is_symlink():
        raise ValueError('Output directory already exists; refusing to mix or replace artifacts')
    if not re.fullmatch(r'[A-Za-z0-9_+.~-]+\.ipk', ipk.name):
        raise ValueError('Input package must have a safe .ipk filename')
    package_bytes = read_limited(ipk)
    reference_bytes = read_limited(reference_module)
    release_bytes = read_limited(kernel_build / 'include/config/kernel.release', 1024)
    abi_bytes = read_limited(kernel_build / '.vermagic', 1024)
    symvers_bytes = read_limited(kernel_build / 'Module.symvers')
    if release_bytes.strip() != KERNEL_RELEASE.encode():
        raise ValueError('Built kernel.release differs from the pinned rescue release')
    if abi_bytes.strip() != KERNEL_ABI.encode():
        raise ValueError('Built OpenWrt .vermagic ABI hash differs from the pinned rescue ABI')
    fields, module_bytes, scripts = inspect_ipk(package_bytes)
    module, reference = inspect_elf(module_bytes), inspect_elf(reference_bytes)
    if not reference['vermagic'].startswith(KERNEL_RELEASE + ' '):
        raise ValueError('Trusted reference is not for the pinned kernel release')
    if module['vermagic'] != reference['vermagic']:
        raise ValueError('Complete module vermagic differs from the trusted rescue module')
    if module['modinfo'].get('name') != ['mtd_rw']:
        raise ValueError('ELF module name must be mtd_rw')
    exports = read_exports(symvers_bytes)
    missing = sorted(set(module['undefined_symbols']) - set(exports))
    if missing:
        raise ValueError('Unexported strong module symbols: ' + ', '.join(missing))
    module['unresolved_weak_symbols'] = sorted(set(module['undefined_weak_symbols']) - set(exports))
    module['symbol_exports'] = {name: exports[name] for name in module['undefined_symbols']}
    module['sha256'] = sha256(module_bytes)
    module['path_in_ipk'] = MODULE_PATH
    report = {
        'validation_schema': 1,
        'validation_kind': 'offline-artifact-compatibility',
        'kernel_release': KERNEL_RELEASE,
        'openwrt_kernel_abi': KERNEL_ABI,
        'kernel_dependency': KERNEL_DEPENDENCY,
        'architecture': ARCHITECTURE,
        'package': fields,
        'ipk': {'filename': ipk.name, 'sha256': sha256(package_bytes), 'size_bytes': len(package_bytes)},
        'module': module,
        'reference_module': {'sha256': sha256(reference_bytes), 'vermagic': reference['vermagic']},
        'kernel_build_inputs': {'kernel.release_sha256': sha256(release_bytes),
                                'openwrt_vermagic_sha256': sha256(abi_bytes),
                                'Module.symvers_sha256': sha256(symvers_bytes)},
        'accepted_stock_maintainer_wrappers': scripts,
        'autoload_present': False,
        'runtime_load_test_performed': False,
        'limitations': ['Static compatibility checks only; no install, load, or flash was performed.',
                        'Reference provenance is established by the caller before this check.',
                        'Module.symvers export availability is checked; runtime symbol resolution is not tested.'],
    }
    # Publish as one directory rename only after every check succeeds. Stage
    # beside the final destination so the rename stays on the same filesystem.
    out.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix='.' + out.name + '-', dir=out.parent))
    try:
        (staging / ipk.name).write_bytes(package_bytes)
        (staging / 'mtd-rw.ko').write_bytes(module_bytes)
        (staging / 'validation.json').write_text(json.dumps(report, indent=2, sort_keys=True) + '\n', encoding='utf-8')
        if out.exists() or out.is_symlink():
            raise ValueError('Output appeared during validation; refusing to replace it')
        staging.rename(out)
    finally:
        if staging.exists():
            shutil.rmtree(staging)
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ipk', type=Path, required=True)
    parser.add_argument('--reference-module', type=Path, required=True)
    parser.add_argument('--kernel-build', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    try:
        report = validate(args.ipk, args.reference_module, args.kernel_build, args.out)
    except (OSError, ValueError) as error:
        parser.exit(1, f'Validation failed: {error}\n')
    print(json.dumps({'validated': str(args.out), 'ipk_sha256': report['ipk']['sha256'],
                      'module_sha256': report['module']['sha256'], 'runtime_load_test_performed': False}))


if __name__ == '__main__':
    main()
